language: R
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm
branches:
  only:
    - master

r_packages:
 - blogdown

before_script:
- nvm install node
- npm install -g netlify-cli
- Rscript -e 'blogdown::install_hugo()'
- mkdir public

script:
- Rscript -e 'blogdown::build_site(local = FALSE)'

after_success:
- ./deploy.sh
