language: r
dist: xenial
latex: false

branches:
  only:
    - master

cache:
  packages: true
  directories:
  - $HOME/.npm

before_script:
- nvm install node
- npm install -g netlify-cli
- mkdir public

script:
- Rscript -e '$ Rscript -e 'install.packages(c("ape"))'


after_success:
- ./deploy.sh
